//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace RealEstate.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RealEstateEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RealEstateEntities object using the connection string found in the 'RealEstateEntities' section of the application configuration file.
        /// </summary>
        public RealEstateEntities() : base("name=RealEstateEntities", "RealEstateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RealEstateEntities object.
        /// </summary>
        public RealEstateEntities(string connectionString) : base(connectionString, "RealEstateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RealEstateEntities object.
        /// </summary>
        public RealEstateEntities(EntityConnection connection) : base(connection, "RealEstateEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Listing> Listings
        {
            get
            {
                if ((_Listings == null))
                {
                    _Listings = base.CreateObjectSet<Listing>("Listings");
                }
                return _Listings;
            }
        }
        private ObjectSet<Listing> _Listings;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Listings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToListings(Listing listing)
        {
            base.AddObject("Listings", listing);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RealEstateModel", Name="Listing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Listing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Listing object.
        /// </summary>
        /// <param name="listingID">Initial value of the ListingID property.</param>
        public static Listing CreateListing(global::System.Int32 listingID)
        {
            Listing listing = new Listing();
            listing.ListingID = listingID;
            return listing;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ListingID
        {
            get
            {
                return _ListingID;
            }
            set
            {
                if (_ListingID != value)
                {
                    OnListingIDChanging(value);
                    ReportPropertyChanging("ListingID");
                    _ListingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ListingID");
                    OnListingIDChanged();
                }
            }
        }
        private global::System.Int32 _ListingID;
        partial void OnListingIDChanging(global::System.Int32 value);
        partial void OnListingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Bedrooms
        {
            get
            {
                return _Bedrooms;
            }
            set
            {
                OnBedroomsChanging(value);
                ReportPropertyChanging("Bedrooms");
                _Bedrooms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bedrooms");
                OnBedroomsChanged();
            }
        }
        private Nullable<global::System.Int32> _Bedrooms;
        partial void OnBedroomsChanging(Nullable<global::System.Int32> value);
        partial void OnBedroomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Rooms
        {
            get
            {
                return _Rooms;
            }
            set
            {
                OnRoomsChanging(value);
                ReportPropertyChanging("Rooms");
                _Rooms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rooms");
                OnRoomsChanged();
            }
        }
        private Nullable<global::System.Int32> _Rooms;
        partial void OnRoomsChanging(Nullable<global::System.Int32> value);
        partial void OnRoomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street1
        {
            get
            {
                return _Street1;
            }
            set
            {
                OnStreet1Changing(value);
                ReportPropertyChanging("Street1");
                _Street1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street1");
                OnStreet1Changed();
            }
        }
        private global::System.String _Street1;
        partial void OnStreet1Changing(global::System.String value);
        partial void OnStreet1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street2
        {
            get
            {
                return _Street2;
            }
            set
            {
                OnStreet2Changing(value);
                ReportPropertyChanging("Street2");
                _Street2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street2");
                OnStreet2Changed();
            }
        }
        private global::System.String _Street2;
        partial void OnStreet2Changing(global::System.String value);
        partial void OnStreet2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();

        #endregion
    
    }

    #endregion
    
}
